modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/StickerFrames/issues"
license="MIT"

[[mods]]
modId="stickerframes"
version="${file.jarVersion}"
displayName="Sticker Frames"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sticker-frames"
authors="Mrbysco"
description='''
A mod that adds item frames that render whatever is in them flat as a sticker.
'''

[[dependencies.stickerframes]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21.4,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.stickerframes]]
modId="neoforge"
type="required"
versionRange="[21.4.0-beta,)"
ordering="NONE"
side="BOTH"